version: 2
jobs:
  test:
    docker:
      - image: 'circleci/node:10-browsers'
    steps:
      - run: echo ':)'
workflows:
  version: 2
  test:
    jobs:
      - test
      - publish_to_npm:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
